worker_app: synapse.app.pusher
worker_name: pusher

# The replication listener on the main synapse process.
worker_replication_host: 127.0.0.1
worker_replication_http_port: 9093

worker_listeners:
 - type: http
   port: 8083
   resources: []

worker_log_config: /conf/workers/pusher_log.yaml